##################################################################################
########### desktop.conf – Pylovara Desktop Engine Configuration #################
##################################################################################

### Desktop Umgebungs-Variablen
export PYLO_DESKTOP_NAME="Pylovara Tiling Desktop"
export PYLO_DESKTOP_VERSION="1.0"
export PYLO_COMPOSITOR="/Pylovara/System/Shell/Vara/dwl.vara"

### Standard Tastenkombinationen (Super-Taste = Mod4)
# Super + Return : Pylovara Terminal
# Super + D      : Programm-Starter (Rofi / FZF / App)
# Super + Shift + Q : Desktop Beenden
# Super + Shift + C : Fenster Schließen

### System-Pfade für Desktop Komponenten
export PYLO_WALLPAPER_DIR="/Pylovara/System/Pictures/Pylovara"
export PYLO_DESKTOP_AUTOSTART="/Pylovara/System/Startsequenz/desktop.autostart-core"