# v0.3 aus gründen veraltet aber wird noch erneuert
# Quelle : /Pylovara/Control/desktop.conf
# === Pylovara MCS Mapping Mapping ===
#source /Pylovara/System/Desktop/Core/mcs-tokenizer.format-core
#source /Pylovara/System/Desktop/Protein/Register/mcs-protein.cmd-register
#source /Pylovara/System/Desktop/Protein/Handler/mcs-protein.container-handler
###############################################################################
# Anvisierter bereich für den ausbau für archlinux hyprland um eine einheitliche 
# entwickler oberfläche für kommende system architekten zu gewehrleisten 
###############################################################################