# === Pylovara Desktop Path Mapping ===
export XDG_CONFIG_HOME="/Pylovara/System/Module/Hyprland/"
export HYPRLAND_CONFIG_PATH="/Pylovara/System/Module/Hyprland/hypr/"
export WAYBAR_CONFIG_FILE="/Pylovara/System/Module/Hyprland/waybar/config"
export WAYBAR_STYLE_FILE="/Pylovara/System/Module/Hyprland/waybar/style.css"
