##################################################################################
########### supertasten.conf – Pylovara Desktop Keybindings Registry ############
##################################################################################

### Haupt-Modifikator
export PYLO_MODKEY="Super"

### Tastenbelegungs-Dokumentation & Befehle
# Super + Return     : Pylovara Terminal
# Super + D          : App-Launcher (Rofi)
# Super + Shift + Q  : Desktop Beenden
# Super + Shift + C  : Fenster Schließen
# Super + Space      : Master / Stack Fokus umschalten
# Super + F          : Floating / Schwebemodus umschalten
# Super + F11        : Vollbild-Modus umschalten

export PYLO_CMD_TERMINAL="/Pylovara/System/Shell/Vara/terminal.vara"
export PYLO_CMD_LAUNCHER="/Pylovara/System/Shell/Vara/rofi.vara -show drun -config /Pylovara/System/Desktop/Programmconfigs/rofi/config.rasi"
export PYLO_CMD_BAR="/Pylovara/System/Shell/Vara/waybar.vara -c /Pylovara/System/Desktop/Programmconfigs/waybar/config.jsonc -s /Pylovara/System/Desktop/Programmconfigs/waybar/style.css"
