##############################################################################
# PYLOVARA SYSTEM KLONE TEST KERNEL UPDATER
##############################################################################
# Hier Ensteht die Tranformer Update Funktion für Zuckünftige
# Test Kernel Updates für Cosed Beta Tester .
#
# Voraussichtliche Zugangsmöglichkeit = 2027
#
# SYSTEM DOWNLOAD WIE ZUGANG WERDEN HIER ENSTEHEN UND WERDEN NUR HIER VON
# EUCH IN EIGENVERANTWORTUNG, VON HIER AUS ABGEGLICHEN !!!!!!!!!!!!!!!!!!!!!!!


